<?php

class FontHandler extends Handler{
    public function handle(XMLReader $request)
    {
        if($request->nodeType === XMLReader::ELEMENT &&
        $request->name === "style:font-face"){
            $family = $request->getAttribute("svg:font-family");
            $size = $this->convertFontSize(
                $request->getAttribute("fo:font-size"));
            $color = $request->getAttribute("fo:color");

            $declarations = [];

            if($family){
                $declarations = "font-family: $family;";
            }
            if($size){
                $declarations = "font-size: $size;";
            }
            if($color){
                $declarations = "color: $color;";
            }

            return '<style>' .
                '.font-' . $this->generateFontClass($family) . '{' .
                implode('; ', $declarations) .
                '}</style>';
        }
        return parent::handle($request); // TODO: Change the autogenerated stub
    }

    private function generateFontClass(string $family): string {
        // Generate unique CSS class name from font family
        return str_replace([' ', '-'], '_', $family);
    }

    private function convertFontSize(string $size): string {
        if (!$size) {
            return '';
        }

        preg_match('/([0-9.]+)(pt)$/', $size, $matches);
        if ($matches) {
            return (float)$matches[1] . 'px';
        }

        return $size;
    }
}
