<?php

class HeaderFooterHandler extends Handler{
    public function handle(XMLReader $request)
    {
        if($request->nodeType === XMLReader::ELEMENT &&
            ($request->name === "style:header" || $request->name === "style:footer")){
            $type = $request->name === "style:header" ? 'header' : 'footer';
            $content = [];

            while ($request->next() &&
                ($request->name !== "style".$type ||
                $request->nodeType !== XMLReader::END_ELEMENT)){

                if($request->nodeType === XMLReader::TEXT){
                    $content[] = htmlspecialchars($request->value);
                }
                elseif($request->nodeType === XMLReader::ELEMENT && $request->name === "text:p"){
                    $content[] = "<div>" . $this->processParagraphContent($request) . "</div>";
                }
            }

            return '<div class="' . $type . '">' .
                implode('', $content) . '</div>';
        }
        return parent::handle($request); // TODO: Change the autogenerated stub
    }

    private function processParagraphContent(XMLReader $reader): string {
        // Process paragraph content including formatting
        return '';
    }
}