<?php

class HyperlinkHandler extends Handler{
    public function handle(XMLReader $request)
    {
        if($request->nodeType === XMLReader::ELEMENT && $request->name === "text:a"){
            $href = $request->getAttribute("xlink:href");
            $title = $request->getAttribute("svg:title");

            $content = "";

            while($request->read() &&
                ($request->name !== "text:a" ||
                    $request->nodeType !== XMLReader::END_ELEMENT)){
                if($request->nodeType === XMLReader::TEXT){
                    $content .= htmlspecialchars($request->value);
                }
            }

            return '<a href="' . htmlspecialchars($href) . '" ' .
                ($title ? 'title="' . htmlspecialchars($title) . '" ' : '') .
                '>' . $content . '</a>';
        }

        return parent::handle($request); // TODO: Change the autogenerated stub
    }
}