<?php

class TableHandler extends Handler{

    public function handle(XMLReader $request)
    {
        if($request->nodeType === XMLReader::ELEMENT &&
            $request->name==="table:table"){

            $htmlTable = ["<table class='ost-table'>"];

            while($request->next() &&
                ($request->name !== "table:table" ||
                    $request->nodeType !== XMLReader::END_ELEMENT)){
                if($request->name === "table:table-row"){
                    $htmlTable[] = "<tr>";

                    while($request->next() &&
                        ($request->name !== "table:table-row" ||
                            $request->nodeType !== XMLReader::END_ELEMENT)){

                        if($request->name === "table:table-cell"){
                            $cellContent = "";

                            while($request->read() &&
                                ($request->name !== "table:table-cell" ||
                                    $request->nodeType !== XMLReader::END_ELEMENT)){
                                if($request->nodeType === XMLReader::TEXT){
                                    $cellContent .= htmlspecialchars($request->value);
                                }
                            }

                            $htmlTable[] = "<td>$cellContent</td>";
                        }
                    }

                    $htmlTable[] = "</tr>";
                }
            }

            $htmlTable[] = "</table>";
            return implode("\n", $htmlTable);
        }
        return parent::handle($request); // TODO: Change the autogenerated stub
    }
}
